name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: gcabrera82/Challenge-GKE

    - name: List files in the repo
      run: ls -al  # Verifica que el Dockerfile esté presente

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    
    - name: "Use gcloud CLI"
      run: gcloud info
      
    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth login
        gcloud auth configure-docker us-east1-docker.pkg.dev
        
    - name: Build and push Docker image
      run: |
        docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-helloworld-py:latest -f Dockerfile .
        docker push us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-helloworld-py:latest
