name: GKE Deploy

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
        
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: "latest"

    - name: Authenticate to GKE
      run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > "${HOME}/gcloud-service-key.json"
      
    - run: |
        gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"
        gcloud --quiet config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud --quiet config set compute/zone ${{ secrets.GCP_ZONE }}
        gcloud --quiet container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/my-app my-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} --record
