name: GKE Connect

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Authenticate to GKE
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > "${HOME}/gcloud-service-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"
        gcloud --quiet config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud --quiet config set compute/zone ${{ secrets.GCP_ZONE }}
        gcloud --quiet container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }}

    - name: Verify connection
      run: |
        kubectl get nodes
